# #index:
# #    path: /
# #    controller: App\Controller\DefaultController::index

# salle_tp_accueil:
#  path: /accueil
#  controller: App\Controller\SalleController::accueil 

# salle_tp_afficher:
#  path: /afficher/{numero}
#  controller: App\Controller\SalleController::afficher

salle_tp :
 resource: routes/salle/routes.yaml
 prefix: /salle

salle_tp_test_chap3et4:
 resource: routes/routingTestChap3et4.yaml
 prefix: /essai
